/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: haykal12321 (https://sketchfab.com/haykal12321)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/star-wars-jedi-fallen-order-bd1-d67b698acba24a829e00fdd4409e1836
title: Star Wars Jedi Fallen Order BD1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.M_0137_Black} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_5} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
