//@ts-nocheck
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BsGithub,BsLinkedin } from 'react-icons/bs'
import {
  Spacer,
  Flex,
  Box,
  MenuItem,
  MenuList,
  MenuButton,
  Text
} from "@chakra-ui/react";
import RetroPC from '../components/RetroPc';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Abylin Johnson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="center">
      <RetroPC/>
      </Flex>
      <Box p="10" borderWidth='0px' borderRadius='lg' >
      <Flex justifyContent="center">
        <Text fontSize={{ base: '24px', md: '40px', lg: '56px' }} fontFamily="Bungee" >Hi, I'M   ABYLIN JOHNSON</Text>
      </Flex>
      <Flex justifyContent="center" fontFamily="Montserrat">
        <Text>FULLSTACK DEVELOPER</Text>
      </Flex>
      <br/>
      <Flex justifyContent="center">
        <Flex p="2">
        <a href='https://www.github.com/abylinjohnson'><BsGithub/></a>
        </Flex>
        <Flex p="2">
        <a href='https://www.linkedin.com/in/abylin-johnson-bb0660150/'><BsLinkedin/></a>
        </Flex>
      </Flex>
      </Box>
      
      

    </div>
  )
}

//"Retro computer" (https://skfb.ly/ou69O) by Urpo is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).
